package main

import (
	"flag"
	"fmt"
	"io"
	"math/rand/v2"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// audioExts is the extension allowlist for the playlist input scan.
var audioExts = map[string]bool{
	".m4a":  true,
	".mp3":  true,
	".wav":  true,
	".flac": true,
	".ogg":  true,
	".aac":  true,
	".qta":  true,
}

// runLs generates a merge playlist from a folder of clips, optionally
// interleaving transition cues from a second folder.
func runLs(args []string) {
	fs := flag.NewFlagSet("reel ls", flag.ExitOnError)
	dir := fs.String("dir", "voice-memo", "input folder of audio clips")
	trans := fs.String("transition", "", "folder of transition cues; empty = no transitions")
	random := fs.Bool("random", true, "randomize transition order (false = sequential cycle)")
	out := fs.String("out", "playlist.txt", "output playlist path (- for stdout)")
	fs.Parse(args)

	clips, err := listAudio(*dir)
	if err != nil {
		die(err)
	}
	if len(clips) == 0 {
		die("no audio files in", *dir)
	}

	var transitions []string
	if *trans != "" {
		transitions, err = listAudio(*trans)
		if err != nil {
			die("transitions:", err)
		}
		if len(transitions) == 0 {
			die("no audio files in transition folder", *trans)
		}
	}

	files := interleave(clips, transitions, *random)

	if *out == "-" {
		writePlaylist(os.Stdout, files, *dir, *trans, *random)
		return
	}
	f, err := os.Create(*out)
	if err != nil {
		die("create playlist:", err)
	}
	defer f.Close()
	if err := writePlaylist(f, files, *dir, *trans, *random); err != nil {
		die("write playlist:", err)
	}
	fmt.Printf("wrote playlist with %d entries (%d clips, %d transitions) -> %s\n",
		len(files), len(clips), max(0, len(files)-len(clips)), *out)
}

// listAudio returns absolute paths of audio files directly inside dir,
// filtered by audioExts and sorted alphabetically.
func listAudio(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !audioExts[strings.ToLower(filepath.Ext(e.Name()))] {
			continue
		}
		abs, err := filepath.Abs(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		files = append(files, abs)
	}
	sort.Strings(files)
	return files, nil
}

// interleave returns clips with a transition inserted between each pair.
// random=true picks each from transitions uniformly; random=false cycles
// through transitions in order. Returns clips unchanged if transitions are
// empty or there's only one clip.
func interleave(clips, transitions []string, random bool) []string {
	if len(clips) <= 1 || len(transitions) == 0 {
		return clips
	}
	out := make([]string, 0, len(clips)*2-1)
	out = append(out, clips[0])
	counter := 0
	for _, c := range clips[1:] {
		var t string
		if random {
			t = transitions[rand.IntN(len(transitions))]
		} else {
			t = transitions[counter%len(transitions)]
			counter++
		}
		out = append(out, t, c)
	}
	return out
}

// writePlaylist writes a header + one path per line. Header lines start
// with `#`; readers skip them.
func writePlaylist(w io.Writer, files []string, dir, trans string, random bool) error {
	fmt.Fprintf(w, "# generated by reel ls at %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(w, "# dir: %s\n", dir)
	if trans != "" {
		mode := "sequential"
		if random {
			mode = "random"
		}
		fmt.Fprintf(w, "# transition: %s (%s)\n", trans, mode)
	}
	fmt.Fprintf(w, "# entries: %d\n\n", len(files))
	for _, f := range files {
		if _, err := fmt.Fprintln(w, f); err != nil {
			return err
		}
	}
	return nil
}
